language: node_js

node_js:
  - "node"

services:
  - postgresql

before_install:
  - psql -c 'create database blog_test' -U postgres
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - psql -U postgres blog_test < test_db.dump
  - yarn install --ignore-scripts --ignore-engines
  - cd client && yarn install --ignore-scripts --ignore-engines
  - cd ..

script:
  - yarn lint
  - yarn lint:client
  - yarn test
