language: node_js

node_js:
  - "node"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn install --ignore-scripts --ignore-engines
  - cd client && yarn install --ignore-scripts --ignore-engines
  - cd ..

script:
  - yarn lint
  - yarn lint:client
